ALTER TABLE notifications
    ADD COLUMN status ENUM('PENDING', 'SENT', 'FAILED') DEFAULT 'PENDING' AFTER sent,
ADD COLUMN priority TINYINT DEFAULT 1 AFTER status, -- 1 = baixa prioridade
ADD COLUMN type VARCHAR(50) DEFAULT 'EMAIL' AFTER priority, -- EMAIL, SMS, PUSH, etc.
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER type,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
UPDATE CURRENT_TIMESTAMP AFTER created_at;
